[build]
  publish = "_site"
  command = "eleventy"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/shop"
  to = "/.netlify/functions/shop"
  status = 200

[[redirects]]
  from = "/shop/product/*"
  to = "/.netlify/functions/odb-product"
  status = 200

 

